'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { TnwAccordionGroup as TnwAccordionGroupElement, defineCustomElement as defineTnwAccordionGroup } from "../../../../stencil-library/dist/components/tnw-accordion-group.js";
import { TnwAccordion as TnwAccordionElement, defineCustomElement as defineTnwAccordion } from "../../../../stencil-library/dist/components/tnw-accordion.js";
import { TnwAlert as TnwAlertElement, defineCustomElement as defineTnwAlert } from "../../../../stencil-library/dist/components/tnw-alert.js";
import { TnwAnchor as TnwAnchorElement, defineCustomElement as defineTnwAnchor } from "../../../../stencil-library/dist/components/tnw-anchor.js";
import { TnwBadge as TnwBadgeElement, defineCustomElement as defineTnwBadge } from "../../../../stencil-library/dist/components/tnw-badge.js";
import { TnwButton as TnwButtonElement, defineCustomElement as defineTnwButton } from "../../../../stencil-library/dist/components/tnw-button.js";
import { TnwCard as TnwCardElement, defineCustomElement as defineTnwCard } from "../../../../stencil-library/dist/components/tnw-card.js";
import { TnwContactBanner as TnwContactBannerElement, defineCustomElement as defineTnwContactBanner } from "../../../../stencil-library/dist/components/tnw-contact-banner.js";
import { TnwDivider as TnwDividerElement, defineCustomElement as defineTnwDivider } from "../../../../stencil-library/dist/components/tnw-divider.js";
import { TnwFooter as TnwFooterElement, defineCustomElement as defineTnwFooter } from "../../../../stencil-library/dist/components/tnw-footer.js";
import { TnwHeaderBanner as TnwHeaderBannerElement, defineCustomElement as defineTnwHeaderBanner } from "../../../../stencil-library/dist/components/tnw-header-banner.js";
import { TnwHeader as TnwHeaderElement, defineCustomElement as defineTnwHeader } from "../../../../stencil-library/dist/components/tnw-header.js";
import { TnwHeading as TnwHeadingElement, defineCustomElement as defineTnwHeading } from "../../../../stencil-library/dist/components/tnw-heading.js";
import { TnwIcon as TnwIconElement, defineCustomElement as defineTnwIcon } from "../../../../stencil-library/dist/components/tnw-icon.js";
import { TnwImage as TnwImageElement, defineCustomElement as defineTnwImage } from "../../../../stencil-library/dist/components/tnw-image.js";
import { TnwInput as TnwInputElement, defineCustomElement as defineTnwInput } from "../../../../stencil-library/dist/components/tnw-input.js";
import { TnwItemsCarousel as TnwItemsCarouselElement, defineCustomElement as defineTnwItemsCarousel } from "../../../../stencil-library/dist/components/tnw-items-carousel.js";
import { TnwLabel as TnwLabelElement, defineCustomElement as defineTnwLabel } from "../../../../stencil-library/dist/components/tnw-label.js";
import { TnwList as TnwListElement, defineCustomElement as defineTnwList } from "../../../../stencil-library/dist/components/tnw-list.js";
import { TnwMultiRowCarousel as TnwMultiRowCarouselElement, defineCustomElement as defineTnwMultiRowCarousel } from "../../../../stencil-library/dist/components/tnw-multi-row-carousel.js";
import { TnwNavbarDropdownMenu as TnwNavbarDropdownMenuElement, defineCustomElement as defineTnwNavbarDropdownMenu } from "../../../../stencil-library/dist/components/tnw-navbar-dropdown-menu.js";
import { TnwNavbarMenuToggler as TnwNavbarMenuTogglerElement, defineCustomElement as defineTnwNavbarMenuToggler } from "../../../../stencil-library/dist/components/tnw-navbar-menu-toggler.js";
import { TnwNavbarMenu as TnwNavbarMenuElement, defineCustomElement as defineTnwNavbarMenu } from "../../../../stencil-library/dist/components/tnw-navbar-menu.js";
import { TnwNavbar as TnwNavbarElement, defineCustomElement as defineTnwNavbar } from "../../../../stencil-library/dist/components/tnw-navbar.js";
import { TnwPortfolioGrid as TnwPortfolioGridElement, defineCustomElement as defineTnwPortfolioGrid } from "../../../../stencil-library/dist/components/tnw-portfolio-grid.js";
import { TnwRating as TnwRatingElement, defineCustomElement as defineTnwRating } from "../../../../stencil-library/dist/components/tnw-rating.js";
import { TnwScrollToTop as TnwScrollToTopElement, defineCustomElement as defineTnwScrollToTop } from "../../../../stencil-library/dist/components/tnw-scroll-to-top.js";
import { TnwSection as TnwSectionElement, defineCustomElement as defineTnwSection } from "../../../../stencil-library/dist/components/tnw-section.js";
import { TnwSelect as TnwSelectElement, defineCustomElement as defineTnwSelect } from "../../../../stencil-library/dist/components/tnw-select.js";
import { TnwTestimonialCard as TnwTestimonialCardElement, defineCustomElement as defineTnwTestimonialCard } from "../../../../stencil-library/dist/components/tnw-testimonial-card.js";
import { TnwText as TnwTextElement, defineCustomElement as defineTnwText } from "../../../../stencil-library/dist/components/tnw-text.js";
import { TnwTextarea as TnwTextareaElement, defineCustomElement as defineTnwTextarea } from "../../../../stencil-library/dist/components/tnw-textarea.js";
import React from 'react';

type TnwAccordionEvents = { onAccordionToggled: EventName<CustomEvent<{ id: string, expanded: boolean }>> };

export const TnwAccordion: StencilReactComponent<TnwAccordionElement, TnwAccordionEvents> = /*@__PURE__*/ createComponent<TnwAccordionElement, TnwAccordionEvents>({
    tagName: 'tnw-accordion',
    elementClass: TnwAccordionElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onAccordionToggled: 'accordionToggled' } as TnwAccordionEvents,
    defineCustomElement: defineTnwAccordion
});

type TnwAccordionGroupEvents = NonNullable<unknown>;

export const TnwAccordionGroup: StencilReactComponent<TnwAccordionGroupElement, TnwAccordionGroupEvents> = /*@__PURE__*/ createComponent<TnwAccordionGroupElement, TnwAccordionGroupEvents>({
    tagName: 'tnw-accordion-group',
    elementClass: TnwAccordionGroupElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwAccordionGroupEvents,
    defineCustomElement: defineTnwAccordionGroup
});

type TnwAlertEvents = NonNullable<unknown>;

export const TnwAlert: StencilReactComponent<TnwAlertElement, TnwAlertEvents> = /*@__PURE__*/ createComponent<TnwAlertElement, TnwAlertEvents>({
    tagName: 'tnw-alert',
    elementClass: TnwAlertElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwAlertEvents,
    defineCustomElement: defineTnwAlert
});

type TnwAnchorEvents = NonNullable<unknown>;

export const TnwAnchor: StencilReactComponent<TnwAnchorElement, TnwAnchorEvents> = /*@__PURE__*/ createComponent<TnwAnchorElement, TnwAnchorEvents>({
    tagName: 'tnw-anchor',
    elementClass: TnwAnchorElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwAnchorEvents,
    defineCustomElement: defineTnwAnchor
});

type TnwBadgeEvents = NonNullable<unknown>;

export const TnwBadge: StencilReactComponent<TnwBadgeElement, TnwBadgeEvents> = /*@__PURE__*/ createComponent<TnwBadgeElement, TnwBadgeEvents>({
    tagName: 'tnw-badge',
    elementClass: TnwBadgeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwBadgeEvents,
    defineCustomElement: defineTnwBadge
});

type TnwButtonEvents = NonNullable<unknown>;

export const TnwButton: StencilReactComponent<TnwButtonElement, TnwButtonEvents> = /*@__PURE__*/ createComponent<TnwButtonElement, TnwButtonEvents>({
    tagName: 'tnw-button',
    elementClass: TnwButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwButtonEvents,
    defineCustomElement: defineTnwButton
});

type TnwCardEvents = NonNullable<unknown>;

export const TnwCard: StencilReactComponent<TnwCardElement, TnwCardEvents> = /*@__PURE__*/ createComponent<TnwCardElement, TnwCardEvents>({
    tagName: 'tnw-card',
    elementClass: TnwCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwCardEvents,
    defineCustomElement: defineTnwCard
});

type TnwContactBannerEvents = NonNullable<unknown>;

export const TnwContactBanner: StencilReactComponent<TnwContactBannerElement, TnwContactBannerEvents> = /*@__PURE__*/ createComponent<TnwContactBannerElement, TnwContactBannerEvents>({
    tagName: 'tnw-contact-banner',
    elementClass: TnwContactBannerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwContactBannerEvents,
    defineCustomElement: defineTnwContactBanner
});

type TnwDividerEvents = NonNullable<unknown>;

export const TnwDivider: StencilReactComponent<TnwDividerElement, TnwDividerEvents> = /*@__PURE__*/ createComponent<TnwDividerElement, TnwDividerEvents>({
    tagName: 'tnw-divider',
    elementClass: TnwDividerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwDividerEvents,
    defineCustomElement: defineTnwDivider
});

type TnwFooterEvents = NonNullable<unknown>;

export const TnwFooter: StencilReactComponent<TnwFooterElement, TnwFooterEvents> = /*@__PURE__*/ createComponent<TnwFooterElement, TnwFooterEvents>({
    tagName: 'tnw-footer',
    elementClass: TnwFooterElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwFooterEvents,
    defineCustomElement: defineTnwFooter
});

type TnwHeaderEvents = NonNullable<unknown>;

export const TnwHeader: StencilReactComponent<TnwHeaderElement, TnwHeaderEvents> = /*@__PURE__*/ createComponent<TnwHeaderElement, TnwHeaderEvents>({
    tagName: 'tnw-header',
    elementClass: TnwHeaderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwHeaderEvents,
    defineCustomElement: defineTnwHeader
});

type TnwHeaderBannerEvents = NonNullable<unknown>;

export const TnwHeaderBanner: StencilReactComponent<TnwHeaderBannerElement, TnwHeaderBannerEvents> = /*@__PURE__*/ createComponent<TnwHeaderBannerElement, TnwHeaderBannerEvents>({
    tagName: 'tnw-header-banner',
    elementClass: TnwHeaderBannerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwHeaderBannerEvents,
    defineCustomElement: defineTnwHeaderBanner
});

type TnwHeadingEvents = NonNullable<unknown>;

export const TnwHeading: StencilReactComponent<TnwHeadingElement, TnwHeadingEvents> = /*@__PURE__*/ createComponent<TnwHeadingElement, TnwHeadingEvents>({
    tagName: 'tnw-heading',
    elementClass: TnwHeadingElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwHeadingEvents,
    defineCustomElement: defineTnwHeading
});

type TnwIconEvents = NonNullable<unknown>;

export const TnwIcon: StencilReactComponent<TnwIconElement, TnwIconEvents> = /*@__PURE__*/ createComponent<TnwIconElement, TnwIconEvents>({
    tagName: 'tnw-icon',
    elementClass: TnwIconElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwIconEvents,
    defineCustomElement: defineTnwIcon
});

type TnwImageEvents = NonNullable<unknown>;

export const TnwImage: StencilReactComponent<TnwImageElement, TnwImageEvents> = /*@__PURE__*/ createComponent<TnwImageElement, TnwImageEvents>({
    tagName: 'tnw-image',
    elementClass: TnwImageElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwImageEvents,
    defineCustomElement: defineTnwImage
});

type TnwInputEvents = NonNullable<unknown>;

export const TnwInput: StencilReactComponent<TnwInputElement, TnwInputEvents> = /*@__PURE__*/ createComponent<TnwInputElement, TnwInputEvents>({
    tagName: 'tnw-input',
    elementClass: TnwInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwInputEvents,
    defineCustomElement: defineTnwInput
});

type TnwItemsCarouselEvents = NonNullable<unknown>;

export const TnwItemsCarousel: StencilReactComponent<TnwItemsCarouselElement, TnwItemsCarouselEvents> = /*@__PURE__*/ createComponent<TnwItemsCarouselElement, TnwItemsCarouselEvents>({
    tagName: 'tnw-items-carousel',
    elementClass: TnwItemsCarouselElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwItemsCarouselEvents,
    defineCustomElement: defineTnwItemsCarousel
});

type TnwLabelEvents = NonNullable<unknown>;

export const TnwLabel: StencilReactComponent<TnwLabelElement, TnwLabelEvents> = /*@__PURE__*/ createComponent<TnwLabelElement, TnwLabelEvents>({
    tagName: 'tnw-label',
    elementClass: TnwLabelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwLabelEvents,
    defineCustomElement: defineTnwLabel
});

type TnwListEvents = NonNullable<unknown>;

export const TnwList: StencilReactComponent<TnwListElement, TnwListEvents> = /*@__PURE__*/ createComponent<TnwListElement, TnwListEvents>({
    tagName: 'tnw-list',
    elementClass: TnwListElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwListEvents,
    defineCustomElement: defineTnwList
});

type TnwMultiRowCarouselEvents = NonNullable<unknown>;

export const TnwMultiRowCarousel: StencilReactComponent<TnwMultiRowCarouselElement, TnwMultiRowCarouselEvents> = /*@__PURE__*/ createComponent<TnwMultiRowCarouselElement, TnwMultiRowCarouselEvents>({
    tagName: 'tnw-multi-row-carousel',
    elementClass: TnwMultiRowCarouselElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwMultiRowCarouselEvents,
    defineCustomElement: defineTnwMultiRowCarousel
});

type TnwNavbarEvents = NonNullable<unknown>;

export const TnwNavbar: StencilReactComponent<TnwNavbarElement, TnwNavbarEvents> = /*@__PURE__*/ createComponent<TnwNavbarElement, TnwNavbarEvents>({
    tagName: 'tnw-navbar',
    elementClass: TnwNavbarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwNavbarEvents,
    defineCustomElement: defineTnwNavbar
});

type TnwNavbarDropdownMenuEvents = NonNullable<unknown>;

export const TnwNavbarDropdownMenu: StencilReactComponent<TnwNavbarDropdownMenuElement, TnwNavbarDropdownMenuEvents> = /*@__PURE__*/ createComponent<TnwNavbarDropdownMenuElement, TnwNavbarDropdownMenuEvents>({
    tagName: 'tnw-navbar-dropdown-menu',
    elementClass: TnwNavbarDropdownMenuElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwNavbarDropdownMenuEvents,
    defineCustomElement: defineTnwNavbarDropdownMenu
});

type TnwNavbarMenuEvents = NonNullable<unknown>;

export const TnwNavbarMenu: StencilReactComponent<TnwNavbarMenuElement, TnwNavbarMenuEvents> = /*@__PURE__*/ createComponent<TnwNavbarMenuElement, TnwNavbarMenuEvents>({
    tagName: 'tnw-navbar-menu',
    elementClass: TnwNavbarMenuElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwNavbarMenuEvents,
    defineCustomElement: defineTnwNavbarMenu
});

type TnwNavbarMenuTogglerEvents = NonNullable<unknown>;

export const TnwNavbarMenuToggler: StencilReactComponent<TnwNavbarMenuTogglerElement, TnwNavbarMenuTogglerEvents> = /*@__PURE__*/ createComponent<TnwNavbarMenuTogglerElement, TnwNavbarMenuTogglerEvents>({
    tagName: 'tnw-navbar-menu-toggler',
    elementClass: TnwNavbarMenuTogglerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwNavbarMenuTogglerEvents,
    defineCustomElement: defineTnwNavbarMenuToggler
});

type TnwPortfolioGridEvents = NonNullable<unknown>;

export const TnwPortfolioGrid: StencilReactComponent<TnwPortfolioGridElement, TnwPortfolioGridEvents> = /*@__PURE__*/ createComponent<TnwPortfolioGridElement, TnwPortfolioGridEvents>({
    tagName: 'tnw-portfolio-grid',
    elementClass: TnwPortfolioGridElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwPortfolioGridEvents,
    defineCustomElement: defineTnwPortfolioGrid
});

type TnwRatingEvents = NonNullable<unknown>;

export const TnwRating: StencilReactComponent<TnwRatingElement, TnwRatingEvents> = /*@__PURE__*/ createComponent<TnwRatingElement, TnwRatingEvents>({
    tagName: 'tnw-rating',
    elementClass: TnwRatingElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwRatingEvents,
    defineCustomElement: defineTnwRating
});

type TnwScrollToTopEvents = NonNullable<unknown>;

export const TnwScrollToTop: StencilReactComponent<TnwScrollToTopElement, TnwScrollToTopEvents> = /*@__PURE__*/ createComponent<TnwScrollToTopElement, TnwScrollToTopEvents>({
    tagName: 'tnw-scroll-to-top',
    elementClass: TnwScrollToTopElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwScrollToTopEvents,
    defineCustomElement: defineTnwScrollToTop
});

type TnwSectionEvents = NonNullable<unknown>;

export const TnwSection: StencilReactComponent<TnwSectionElement, TnwSectionEvents> = /*@__PURE__*/ createComponent<TnwSectionElement, TnwSectionEvents>({
    tagName: 'tnw-section',
    elementClass: TnwSectionElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwSectionEvents,
    defineCustomElement: defineTnwSection
});

type TnwSelectEvents = { onOptionSelected: EventName<CustomEvent<string>> };

export const TnwSelect: StencilReactComponent<TnwSelectElement, TnwSelectEvents> = /*@__PURE__*/ createComponent<TnwSelectElement, TnwSelectEvents>({
    tagName: 'tnw-select',
    elementClass: TnwSelectElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onOptionSelected: 'optionSelected' } as TnwSelectEvents,
    defineCustomElement: defineTnwSelect
});

type TnwTestimonialCardEvents = NonNullable<unknown>;

export const TnwTestimonialCard: StencilReactComponent<TnwTestimonialCardElement, TnwTestimonialCardEvents> = /*@__PURE__*/ createComponent<TnwTestimonialCardElement, TnwTestimonialCardEvents>({
    tagName: 'tnw-testimonial-card',
    elementClass: TnwTestimonialCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwTestimonialCardEvents,
    defineCustomElement: defineTnwTestimonialCard
});

type TnwTextEvents = NonNullable<unknown>;

export const TnwText: StencilReactComponent<TnwTextElement, TnwTextEvents> = /*@__PURE__*/ createComponent<TnwTextElement, TnwTextEvents>({
    tagName: 'tnw-text',
    elementClass: TnwTextElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwTextEvents,
    defineCustomElement: defineTnwText
});

type TnwTextareaEvents = NonNullable<unknown>;

export const TnwTextarea: StencilReactComponent<TnwTextareaElement, TnwTextareaEvents> = /*@__PURE__*/ createComponent<TnwTextareaElement, TnwTextareaEvents>({
    tagName: 'tnw-textarea',
    elementClass: TnwTextareaElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwTextareaEvents,
    defineCustomElement: defineTnwTextarea
});
