'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type TnwSelectCustomEvent, type TnwSelectOption } from "@technway/stencil-library";
import { TnwAccordionGroup as TnwAccordionGroupElement, defineCustomElement as defineTnwAccordionGroup } from "@technway/stencil-library/components/tnw-accordion-group.js";
import { TnwAccordion as TnwAccordionElement, defineCustomElement as defineTnwAccordion } from "@technway/stencil-library/components/tnw-accordion.js";
import { TnwAlert as TnwAlertElement, defineCustomElement as defineTnwAlert } from "@technway/stencil-library/components/tnw-alert.js";
import { TnwAnchorStyler as TnwAnchorStylerElement, defineCustomElement as defineTnwAnchorStyler } from "@technway/stencil-library/components/tnw-anchor-styler.js";
import { TnwAnchor as TnwAnchorElement, defineCustomElement as defineTnwAnchor } from "@technway/stencil-library/components/tnw-anchor.js";
import { TnwBadge as TnwBadgeElement, defineCustomElement as defineTnwBadge } from "@technway/stencil-library/components/tnw-badge.js";
import { TnwBanner as TnwBannerElement, defineCustomElement as defineTnwBanner } from "@technway/stencil-library/components/tnw-banner.js";
import { TnwButton as TnwButtonElement, defineCustomElement as defineTnwButton } from "@technway/stencil-library/components/tnw-button.js";
import { TnwCard as TnwCardElement, defineCustomElement as defineTnwCard } from "@technway/stencil-library/components/tnw-card.js";
import { TnwContactBanner as TnwContactBannerElement, defineCustomElement as defineTnwContactBanner } from "@technway/stencil-library/components/tnw-contact-banner.js";
import { TnwCopyrightsFooter as TnwCopyrightsFooterElement, defineCustomElement as defineTnwCopyrightsFooter } from "@technway/stencil-library/components/tnw-copyrights-footer.js";
import { TnwDivider as TnwDividerElement, defineCustomElement as defineTnwDivider } from "@technway/stencil-library/components/tnw-divider.js";
import { TnwFooter as TnwFooterElement, defineCustomElement as defineTnwFooter } from "@technway/stencil-library/components/tnw-footer.js";
import { TnwHeaderBanner as TnwHeaderBannerElement, defineCustomElement as defineTnwHeaderBanner } from "@technway/stencil-library/components/tnw-header-banner.js";
import { TnwHeader as TnwHeaderElement, defineCustomElement as defineTnwHeader } from "@technway/stencil-library/components/tnw-header.js";
import { TnwHeading as TnwHeadingElement, defineCustomElement as defineTnwHeading } from "@technway/stencil-library/components/tnw-heading.js";
import { TnwIcon as TnwIconElement, defineCustomElement as defineTnwIcon } from "@technway/stencil-library/components/tnw-icon.js";
import { TnwImage as TnwImageElement, defineCustomElement as defineTnwImage } from "@technway/stencil-library/components/tnw-image.js";
import { TnwInputForm as TnwInputFormElement, defineCustomElement as defineTnwInputForm } from "@technway/stencil-library/components/tnw-input-form.js";
import { TnwInput as TnwInputElement, defineCustomElement as defineTnwInput } from "@technway/stencil-library/components/tnw-input.js";
import { TnwItemsCarousel as TnwItemsCarouselElement, defineCustomElement as defineTnwItemsCarousel } from "@technway/stencil-library/components/tnw-items-carousel.js";
import { TnwLabel as TnwLabelElement, defineCustomElement as defineTnwLabel } from "@technway/stencil-library/components/tnw-label.js";
import { TnwList as TnwListElement, defineCustomElement as defineTnwList } from "@technway/stencil-library/components/tnw-list.js";
import { TnwNavbar as TnwNavbarElement, defineCustomElement as defineTnwNavbar } from "@technway/stencil-library/components/tnw-navbar.js";
import { TnwPortfolioGrid as TnwPortfolioGridElement, defineCustomElement as defineTnwPortfolioGrid } from "@technway/stencil-library/components/tnw-portfolio-grid.js";
import { TnwRating as TnwRatingElement, defineCustomElement as defineTnwRating } from "@technway/stencil-library/components/tnw-rating.js";
import { TnwRowsCarousel as TnwRowsCarouselElement, defineCustomElement as defineTnwRowsCarousel } from "@technway/stencil-library/components/tnw-rows-carousel.js";
import { TnwScrollToTop as TnwScrollToTopElement, defineCustomElement as defineTnwScrollToTop } from "@technway/stencil-library/components/tnw-scroll-to-top.js";
import { TnwSearchInput as TnwSearchInputElement, defineCustomElement as defineTnwSearchInput } from "@technway/stencil-library/components/tnw-search-input.js";
import { TnwSection as TnwSectionElement, defineCustomElement as defineTnwSection } from "@technway/stencil-library/components/tnw-section.js";
import { TnwSelect as TnwSelectElement, defineCustomElement as defineTnwSelect } from "@technway/stencil-library/components/tnw-select.js";
import { TnwSubscriptionForm as TnwSubscriptionFormElement, defineCustomElement as defineTnwSubscriptionForm } from "@technway/stencil-library/components/tnw-subscription-form.js";
import { TnwTestimonialCard as TnwTestimonialCardElement, defineCustomElement as defineTnwTestimonialCard } from "@technway/stencil-library/components/tnw-testimonial-card.js";
import { TnwText as TnwTextElement, defineCustomElement as defineTnwText } from "@technway/stencil-library/components/tnw-text.js";
import { TnwTextarea as TnwTextareaElement, defineCustomElement as defineTnwTextarea } from "@technway/stencil-library/components/tnw-textarea.js";
import React from 'react';

type TnwAccordionEvents = { onAccordionToggled: EventName<CustomEvent<{ id: string, expanded: boolean }>> };

export const TnwAccordion: StencilReactComponent<TnwAccordionElement, TnwAccordionEvents> = /*@__PURE__*/ createComponent<TnwAccordionElement, TnwAccordionEvents>({
    tagName: 'tnw-accordion',
    elementClass: TnwAccordionElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onAccordionToggled: 'accordionToggled' } as TnwAccordionEvents,
    defineCustomElement: defineTnwAccordion
});

type TnwAccordionGroupEvents = NonNullable<unknown>;

export const TnwAccordionGroup: StencilReactComponent<TnwAccordionGroupElement, TnwAccordionGroupEvents> = /*@__PURE__*/ createComponent<TnwAccordionGroupElement, TnwAccordionGroupEvents>({
    tagName: 'tnw-accordion-group',
    elementClass: TnwAccordionGroupElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwAccordionGroupEvents,
    defineCustomElement: defineTnwAccordionGroup
});

type TnwAlertEvents = NonNullable<unknown>;

export const TnwAlert: StencilReactComponent<TnwAlertElement, TnwAlertEvents> = /*@__PURE__*/ createComponent<TnwAlertElement, TnwAlertEvents>({
    tagName: 'tnw-alert',
    elementClass: TnwAlertElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwAlertEvents,
    defineCustomElement: defineTnwAlert
});

type TnwAnchorEvents = NonNullable<unknown>;

export const TnwAnchor: StencilReactComponent<TnwAnchorElement, TnwAnchorEvents> = /*@__PURE__*/ createComponent<TnwAnchorElement, TnwAnchorEvents>({
    tagName: 'tnw-anchor',
    elementClass: TnwAnchorElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwAnchorEvents,
    defineCustomElement: defineTnwAnchor
});

type TnwAnchorStylerEvents = NonNullable<unknown>;

export const TnwAnchorStyler: StencilReactComponent<TnwAnchorStylerElement, TnwAnchorStylerEvents> = /*@__PURE__*/ createComponent<TnwAnchorStylerElement, TnwAnchorStylerEvents>({
    tagName: 'tnw-anchor-styler',
    elementClass: TnwAnchorStylerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwAnchorStylerEvents,
    defineCustomElement: defineTnwAnchorStyler
});

type TnwBadgeEvents = NonNullable<unknown>;

export const TnwBadge: StencilReactComponent<TnwBadgeElement, TnwBadgeEvents> = /*@__PURE__*/ createComponent<TnwBadgeElement, TnwBadgeEvents>({
    tagName: 'tnw-badge',
    elementClass: TnwBadgeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwBadgeEvents,
    defineCustomElement: defineTnwBadge
});

type TnwBannerEvents = NonNullable<unknown>;

export const TnwBanner: StencilReactComponent<TnwBannerElement, TnwBannerEvents> = /*@__PURE__*/ createComponent<TnwBannerElement, TnwBannerEvents>({
    tagName: 'tnw-banner',
    elementClass: TnwBannerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwBannerEvents,
    defineCustomElement: defineTnwBanner
});

type TnwButtonEvents = NonNullable<unknown>;

export const TnwButton: StencilReactComponent<TnwButtonElement, TnwButtonEvents> = /*@__PURE__*/ createComponent<TnwButtonElement, TnwButtonEvents>({
    tagName: 'tnw-button',
    elementClass: TnwButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwButtonEvents,
    defineCustomElement: defineTnwButton
});

type TnwCardEvents = NonNullable<unknown>;

export const TnwCard: StencilReactComponent<TnwCardElement, TnwCardEvents> = /*@__PURE__*/ createComponent<TnwCardElement, TnwCardEvents>({
    tagName: 'tnw-card',
    elementClass: TnwCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwCardEvents,
    defineCustomElement: defineTnwCard
});

type TnwContactBannerEvents = NonNullable<unknown>;

export const TnwContactBanner: StencilReactComponent<TnwContactBannerElement, TnwContactBannerEvents> = /*@__PURE__*/ createComponent<TnwContactBannerElement, TnwContactBannerEvents>({
    tagName: 'tnw-contact-banner',
    elementClass: TnwContactBannerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwContactBannerEvents,
    defineCustomElement: defineTnwContactBanner
});

type TnwCopyrightsFooterEvents = NonNullable<unknown>;

export const TnwCopyrightsFooter: StencilReactComponent<TnwCopyrightsFooterElement, TnwCopyrightsFooterEvents> = /*@__PURE__*/ createComponent<TnwCopyrightsFooterElement, TnwCopyrightsFooterEvents>({
    tagName: 'tnw-copyrights-footer',
    elementClass: TnwCopyrightsFooterElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwCopyrightsFooterEvents,
    defineCustomElement: defineTnwCopyrightsFooter
});

type TnwDividerEvents = NonNullable<unknown>;

export const TnwDivider: StencilReactComponent<TnwDividerElement, TnwDividerEvents> = /*@__PURE__*/ createComponent<TnwDividerElement, TnwDividerEvents>({
    tagName: 'tnw-divider',
    elementClass: TnwDividerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwDividerEvents,
    defineCustomElement: defineTnwDivider
});

type TnwFooterEvents = NonNullable<unknown>;

export const TnwFooter: StencilReactComponent<TnwFooterElement, TnwFooterEvents> = /*@__PURE__*/ createComponent<TnwFooterElement, TnwFooterEvents>({
    tagName: 'tnw-footer',
    elementClass: TnwFooterElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwFooterEvents,
    defineCustomElement: defineTnwFooter
});

type TnwHeaderEvents = NonNullable<unknown>;

export const TnwHeader: StencilReactComponent<TnwHeaderElement, TnwHeaderEvents> = /*@__PURE__*/ createComponent<TnwHeaderElement, TnwHeaderEvents>({
    tagName: 'tnw-header',
    elementClass: TnwHeaderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwHeaderEvents,
    defineCustomElement: defineTnwHeader
});

type TnwHeaderBannerEvents = NonNullable<unknown>;

export const TnwHeaderBanner: StencilReactComponent<TnwHeaderBannerElement, TnwHeaderBannerEvents> = /*@__PURE__*/ createComponent<TnwHeaderBannerElement, TnwHeaderBannerEvents>({
    tagName: 'tnw-header-banner',
    elementClass: TnwHeaderBannerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwHeaderBannerEvents,
    defineCustomElement: defineTnwHeaderBanner
});

type TnwHeadingEvents = NonNullable<unknown>;

export const TnwHeading: StencilReactComponent<TnwHeadingElement, TnwHeadingEvents> = /*@__PURE__*/ createComponent<TnwHeadingElement, TnwHeadingEvents>({
    tagName: 'tnw-heading',
    elementClass: TnwHeadingElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwHeadingEvents,
    defineCustomElement: defineTnwHeading
});

type TnwIconEvents = NonNullable<unknown>;

export const TnwIcon: StencilReactComponent<TnwIconElement, TnwIconEvents> = /*@__PURE__*/ createComponent<TnwIconElement, TnwIconEvents>({
    tagName: 'tnw-icon',
    elementClass: TnwIconElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwIconEvents,
    defineCustomElement: defineTnwIcon
});

type TnwImageEvents = NonNullable<unknown>;

export const TnwImage: StencilReactComponent<TnwImageElement, TnwImageEvents> = /*@__PURE__*/ createComponent<TnwImageElement, TnwImageEvents>({
    tagName: 'tnw-image',
    elementClass: TnwImageElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwImageEvents,
    defineCustomElement: defineTnwImage
});

type TnwInputEvents = {
    onInputChanged: EventName<CustomEvent<string>>,
    onValidationFailed: EventName<CustomEvent<{ inputId: string; error: string }>>
};

export const TnwInput: StencilReactComponent<TnwInputElement, TnwInputEvents> = /*@__PURE__*/ createComponent<TnwInputElement, TnwInputEvents>({
    tagName: 'tnw-input',
    elementClass: TnwInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onInputChanged: 'inputChanged',
        onValidationFailed: 'validationFailed'
    } as TnwInputEvents,
    defineCustomElement: defineTnwInput
});

type TnwInputFormEvents = NonNullable<unknown>;

export const TnwInputForm: StencilReactComponent<TnwInputFormElement, TnwInputFormEvents> = /*@__PURE__*/ createComponent<TnwInputFormElement, TnwInputFormEvents>({
    tagName: 'tnw-input-form',
    elementClass: TnwInputFormElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwInputFormEvents,
    defineCustomElement: defineTnwInputForm
});

type TnwItemsCarouselEvents = NonNullable<unknown>;

export const TnwItemsCarousel: StencilReactComponent<TnwItemsCarouselElement, TnwItemsCarouselEvents> = /*@__PURE__*/ createComponent<TnwItemsCarouselElement, TnwItemsCarouselEvents>({
    tagName: 'tnw-items-carousel',
    elementClass: TnwItemsCarouselElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwItemsCarouselEvents,
    defineCustomElement: defineTnwItemsCarousel
});

type TnwLabelEvents = NonNullable<unknown>;

export const TnwLabel: StencilReactComponent<TnwLabelElement, TnwLabelEvents> = /*@__PURE__*/ createComponent<TnwLabelElement, TnwLabelEvents>({
    tagName: 'tnw-label',
    elementClass: TnwLabelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwLabelEvents,
    defineCustomElement: defineTnwLabel
});

type TnwListEvents = NonNullable<unknown>;

export const TnwList: StencilReactComponent<TnwListElement, TnwListEvents> = /*@__PURE__*/ createComponent<TnwListElement, TnwListEvents>({
    tagName: 'tnw-list',
    elementClass: TnwListElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwListEvents,
    defineCustomElement: defineTnwList
});

type TnwNavbarEvents = {
    onTnwMenuToggle: EventName<CustomEvent<{ isOpen: boolean }>>,
    onTnwMenuVisibilityChange: EventName<CustomEvent<{ isMenuHidden: boolean, windowWidth: number }>>,
    onTnwScrollChange: EventName<CustomEvent<{ scrollY: number }>>
};

export const TnwNavbar: StencilReactComponent<TnwNavbarElement, TnwNavbarEvents> = /*@__PURE__*/ createComponent<TnwNavbarElement, TnwNavbarEvents>({
    tagName: 'tnw-navbar',
    elementClass: TnwNavbarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onTnwMenuToggle: 'tnwMenuToggle',
        onTnwMenuVisibilityChange: 'tnwMenuVisibilityChange',
        onTnwScrollChange: 'tnwScrollChange'
    } as TnwNavbarEvents,
    defineCustomElement: defineTnwNavbar
});

type TnwPortfolioGridEvents = NonNullable<unknown>;

export const TnwPortfolioGrid: StencilReactComponent<TnwPortfolioGridElement, TnwPortfolioGridEvents> = /*@__PURE__*/ createComponent<TnwPortfolioGridElement, TnwPortfolioGridEvents>({
    tagName: 'tnw-portfolio-grid',
    elementClass: TnwPortfolioGridElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwPortfolioGridEvents,
    defineCustomElement: defineTnwPortfolioGrid
});

type TnwRatingEvents = NonNullable<unknown>;

export const TnwRating: StencilReactComponent<TnwRatingElement, TnwRatingEvents> = /*@__PURE__*/ createComponent<TnwRatingElement, TnwRatingEvents>({
    tagName: 'tnw-rating',
    elementClass: TnwRatingElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwRatingEvents,
    defineCustomElement: defineTnwRating
});

type TnwRowsCarouselEvents = {
    onTnwRowPause: EventName<CustomEvent<number>>,
    onTnwRowResume: EventName<CustomEvent<number>>
};

export const TnwRowsCarousel: StencilReactComponent<TnwRowsCarouselElement, TnwRowsCarouselEvents> = /*@__PURE__*/ createComponent<TnwRowsCarouselElement, TnwRowsCarouselEvents>({
    tagName: 'tnw-rows-carousel',
    elementClass: TnwRowsCarouselElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onTnwRowPause: 'tnwRowPause',
        onTnwRowResume: 'tnwRowResume'
    } as TnwRowsCarouselEvents,
    defineCustomElement: defineTnwRowsCarousel
});

type TnwScrollToTopEvents = {
    onVisible: EventName<CustomEvent<{ isVisible: boolean; scrollY: number }>>,
    onScrollToTopClicked: EventName<CustomEvent<{ scrollY: number }>>
};

export const TnwScrollToTop: StencilReactComponent<TnwScrollToTopElement, TnwScrollToTopEvents> = /*@__PURE__*/ createComponent<TnwScrollToTopElement, TnwScrollToTopEvents>({
    tagName: 'tnw-scroll-to-top',
    elementClass: TnwScrollToTopElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onVisible: 'visible',
        onScrollToTopClicked: 'scrollToTopClicked'
    } as TnwScrollToTopEvents,
    defineCustomElement: defineTnwScrollToTop
});

type TnwSearchInputEvents = { onInputChangedOnType: EventName<CustomEvent<string>> };

export const TnwSearchInput: StencilReactComponent<TnwSearchInputElement, TnwSearchInputEvents> = /*@__PURE__*/ createComponent<TnwSearchInputElement, TnwSearchInputEvents>({
    tagName: 'tnw-search-input',
    elementClass: TnwSearchInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onInputChangedOnType: 'inputChangedOnType' } as TnwSearchInputEvents,
    defineCustomElement: defineTnwSearchInput
});

type TnwSectionEvents = NonNullable<unknown>;

export const TnwSection: StencilReactComponent<TnwSectionElement, TnwSectionEvents> = /*@__PURE__*/ createComponent<TnwSectionElement, TnwSectionEvents>({
    tagName: 'tnw-section',
    elementClass: TnwSectionElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwSectionEvents,
    defineCustomElement: defineTnwSection
});

type TnwSelectEvents = {
    onOptionSelected: EventName<TnwSelectCustomEvent<TnwSelectOption>>,
    onDropdownToggled: EventName<CustomEvent<{ isOpen: boolean }>>
};

export const TnwSelect: StencilReactComponent<TnwSelectElement, TnwSelectEvents> = /*@__PURE__*/ createComponent<TnwSelectElement, TnwSelectEvents>({
    tagName: 'tnw-select',
    elementClass: TnwSelectElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onOptionSelected: 'optionSelected',
        onDropdownToggled: 'dropdownToggled'
    } as TnwSelectEvents,
    defineCustomElement: defineTnwSelect
});

type TnwSubscriptionFormEvents = NonNullable<unknown>;

export const TnwSubscriptionForm: StencilReactComponent<TnwSubscriptionFormElement, TnwSubscriptionFormEvents> = /*@__PURE__*/ createComponent<TnwSubscriptionFormElement, TnwSubscriptionFormEvents>({
    tagName: 'tnw-subscription-form',
    elementClass: TnwSubscriptionFormElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwSubscriptionFormEvents,
    defineCustomElement: defineTnwSubscriptionForm
});

type TnwTestimonialCardEvents = NonNullable<unknown>;

export const TnwTestimonialCard: StencilReactComponent<TnwTestimonialCardElement, TnwTestimonialCardEvents> = /*@__PURE__*/ createComponent<TnwTestimonialCardElement, TnwTestimonialCardEvents>({
    tagName: 'tnw-testimonial-card',
    elementClass: TnwTestimonialCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwTestimonialCardEvents,
    defineCustomElement: defineTnwTestimonialCard
});

type TnwTextEvents = NonNullable<unknown>;

export const TnwText: StencilReactComponent<TnwTextElement, TnwTextEvents> = /*@__PURE__*/ createComponent<TnwTextElement, TnwTextEvents>({
    tagName: 'tnw-text',
    elementClass: TnwTextElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TnwTextEvents,
    defineCustomElement: defineTnwText
});

type TnwTextareaEvents = {
    onTextareaChanged: EventName<CustomEvent<string>>,
    onValidationFailed: EventName<CustomEvent<{ textareaId: string; error: string }>>
};

export const TnwTextarea: StencilReactComponent<TnwTextareaElement, TnwTextareaEvents> = /*@__PURE__*/ createComponent<TnwTextareaElement, TnwTextareaEvents>({
    tagName: 'tnw-textarea',
    elementClass: TnwTextareaElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onTextareaChanged: 'textareaChanged',
        onValidationFailed: 'validationFailed'
    } as TnwTextareaEvents,
    defineCustomElement: defineTnwTextarea
});
