/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import { type TnwSelectCustomEvent, type TnwSelectOption } from "@technway/stencil-library";
import { TnwAccordionGroup as TnwAccordionGroupElement, defineCustomElement as defineTnwAccordionGroup } from "@technway/stencil-library/components/tnw-accordion-group.js";
import { TnwAccordion as TnwAccordionElement, defineCustomElement as defineTnwAccordion } from "@technway/stencil-library/components/tnw-accordion.js";
import { TnwAlert as TnwAlertElement, defineCustomElement as defineTnwAlert } from "@technway/stencil-library/components/tnw-alert.js";
import { TnwAnchorStyler as TnwAnchorStylerElement, defineCustomElement as defineTnwAnchorStyler } from "@technway/stencil-library/components/tnw-anchor-styler.js";
import { TnwAnchor as TnwAnchorElement, defineCustomElement as defineTnwAnchor } from "@technway/stencil-library/components/tnw-anchor.js";
import { TnwBadge as TnwBadgeElement, defineCustomElement as defineTnwBadge } from "@technway/stencil-library/components/tnw-badge.js";
import { TnwBanner as TnwBannerElement, defineCustomElement as defineTnwBanner } from "@technway/stencil-library/components/tnw-banner.js";
import { TnwButton as TnwButtonElement, defineCustomElement as defineTnwButton } from "@technway/stencil-library/components/tnw-button.js";
import { TnwCard as TnwCardElement, defineCustomElement as defineTnwCard } from "@technway/stencil-library/components/tnw-card.js";
import { TnwContactBanner as TnwContactBannerElement, defineCustomElement as defineTnwContactBanner } from "@technway/stencil-library/components/tnw-contact-banner.js";
import { TnwCopyrightsFooter as TnwCopyrightsFooterElement, defineCustomElement as defineTnwCopyrightsFooter } from "@technway/stencil-library/components/tnw-copyrights-footer.js";
import { TnwDivider as TnwDividerElement, defineCustomElement as defineTnwDivider } from "@technway/stencil-library/components/tnw-divider.js";
import { TnwFooter as TnwFooterElement, defineCustomElement as defineTnwFooter } from "@technway/stencil-library/components/tnw-footer.js";
import { TnwHeaderBanner as TnwHeaderBannerElement, defineCustomElement as defineTnwHeaderBanner } from "@technway/stencil-library/components/tnw-header-banner.js";
import { TnwHeader as TnwHeaderElement, defineCustomElement as defineTnwHeader } from "@technway/stencil-library/components/tnw-header.js";
import { TnwHeading as TnwHeadingElement, defineCustomElement as defineTnwHeading } from "@technway/stencil-library/components/tnw-heading.js";
import { TnwIcon as TnwIconElement, defineCustomElement as defineTnwIcon } from "@technway/stencil-library/components/tnw-icon.js";
import { TnwImage as TnwImageElement, defineCustomElement as defineTnwImage } from "@technway/stencil-library/components/tnw-image.js";
import { TnwInputForm as TnwInputFormElement, defineCustomElement as defineTnwInputForm } from "@technway/stencil-library/components/tnw-input-form.js";
import { TnwInput as TnwInputElement, defineCustomElement as defineTnwInput } from "@technway/stencil-library/components/tnw-input.js";
import { TnwItemsCarousel as TnwItemsCarouselElement, defineCustomElement as defineTnwItemsCarousel } from "@technway/stencil-library/components/tnw-items-carousel.js";
import { TnwLabel as TnwLabelElement, defineCustomElement as defineTnwLabel } from "@technway/stencil-library/components/tnw-label.js";
import { TnwList as TnwListElement, defineCustomElement as defineTnwList } from "@technway/stencil-library/components/tnw-list.js";
import { TnwNavbar as TnwNavbarElement, defineCustomElement as defineTnwNavbar } from "@technway/stencil-library/components/tnw-navbar.js";
import { TnwPortfolioGrid as TnwPortfolioGridElement, defineCustomElement as defineTnwPortfolioGrid } from "@technway/stencil-library/components/tnw-portfolio-grid.js";
import { TnwRating as TnwRatingElement, defineCustomElement as defineTnwRating } from "@technway/stencil-library/components/tnw-rating.js";
import { TnwRowsCarousel as TnwRowsCarouselElement, defineCustomElement as defineTnwRowsCarousel } from "@technway/stencil-library/components/tnw-rows-carousel.js";
import { TnwScrollToTop as TnwScrollToTopElement, defineCustomElement as defineTnwScrollToTop } from "@technway/stencil-library/components/tnw-scroll-to-top.js";
import { TnwSearchInput as TnwSearchInputElement, defineCustomElement as defineTnwSearchInput } from "@technway/stencil-library/components/tnw-search-input.js";
import { TnwSection as TnwSectionElement, defineCustomElement as defineTnwSection } from "@technway/stencil-library/components/tnw-section.js";
import { TnwSelect as TnwSelectElement, defineCustomElement as defineTnwSelect } from "@technway/stencil-library/components/tnw-select.js";
import { TnwSubscriptionForm as TnwSubscriptionFormElement, defineCustomElement as defineTnwSubscriptionForm } from "@technway/stencil-library/components/tnw-subscription-form.js";
import { TnwTestimonialCard as TnwTestimonialCardElement, defineCustomElement as defineTnwTestimonialCard } from "@technway/stencil-library/components/tnw-testimonial-card.js";
import { TnwText as TnwTextElement, defineCustomElement as defineTnwText } from "@technway/stencil-library/components/tnw-text.js";
import { TnwTextarea as TnwTextareaElement, defineCustomElement as defineTnwTextarea } from "@technway/stencil-library/components/tnw-textarea.js";
import React from 'react';

type TnwAccordionEvents = { onAccordionToggled: EventName<CustomEvent<{ id: string, expanded: boolean }>> };

export const TnwAccordion: StencilReactComponent<TnwAccordionElement, TnwAccordionEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwAccordionElement, TnwAccordionEvents>({
        tagName: 'tnw-accordion',
        elementClass: TnwAccordionElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onAccordionToggled: 'accordionToggled' } as TnwAccordionEvents,
        defineCustomElement: defineTnwAccordion
    })
    : /*@__PURE__*/ createSSRComponent<TnwAccordionElement, TnwAccordionEvents>({
        tagName: 'tnw-accordion',
        properties: {
            heading: 'heading',
            content: 'content',
            expand: 'expand',
            accordionId: 'accordion-id',
            appearanceColor: 'appearance-color',
            color: 'color',
            appearance: 'appearance',
            enableCustomExpandIcon: 'enable-custom-expand-icon',
            disableExpandIconRotate: 'disable-expand-icon-rotate',
            borderRadius: 'border-radius'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwAccordionGroupEvents = NonNullable<unknown>;

export const TnwAccordionGroup: StencilReactComponent<TnwAccordionGroupElement, TnwAccordionGroupEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwAccordionGroupElement, TnwAccordionGroupEvents>({
        tagName: 'tnw-accordion-group',
        elementClass: TnwAccordionGroupElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwAccordionGroupEvents,
        defineCustomElement: defineTnwAccordionGroup
    })
    : /*@__PURE__*/ createSSRComponent<TnwAccordionGroupElement, TnwAccordionGroupEvents>({
        tagName: 'tnw-accordion-group',
        properties: { singleExpand: 'single-expand' },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwAlertEvents = NonNullable<unknown>;

export const TnwAlert: StencilReactComponent<TnwAlertElement, TnwAlertEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwAlertElement, TnwAlertEvents>({
        tagName: 'tnw-alert',
        elementClass: TnwAlertElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwAlertEvents,
        defineCustomElement: defineTnwAlert
    })
    : /*@__PURE__*/ createSSRComponent<TnwAlertElement, TnwAlertEvents>({
        tagName: 'tnw-alert',
        properties: {
            alertId: 'alert-id',
            message: 'message',
            size: 'size',
            appearance: 'appearance',
            appearanceColor: 'appearance-color',
            isHidden: 'is-hidden',
            borderRadius: 'border-radius'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwAnchorEvents = NonNullable<unknown>;

export const TnwAnchor: StencilReactComponent<TnwAnchorElement, TnwAnchorEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwAnchorElement, TnwAnchorEvents>({
        tagName: 'tnw-anchor',
        elementClass: TnwAnchorElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwAnchorEvents,
        defineCustomElement: defineTnwAnchor
    })
    : /*@__PURE__*/ createSSRComponent<TnwAnchorElement, TnwAnchorEvents>({
        tagName: 'tnw-anchor',
        properties: {
            href: 'href',
            text: 'text',
            color: 'color',
            size: 'size',
            labelAria: 'label-aria',
            textDecoration: 'text-decoration',
            newTab: 'new-tab',
            hideNewTabIcon: 'hide-new-tab-icon'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwAnchorStylerEvents = NonNullable<unknown>;

export const TnwAnchorStyler: StencilReactComponent<TnwAnchorStylerElement, TnwAnchorStylerEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwAnchorStylerElement, TnwAnchorStylerEvents>({
        tagName: 'tnw-anchor-styler',
        elementClass: TnwAnchorStylerElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwAnchorStylerEvents,
        defineCustomElement: defineTnwAnchorStyler
    })
    : /*@__PURE__*/ createSSRComponent<TnwAnchorStylerElement, TnwAnchorStylerEvents>({
        tagName: 'tnw-anchor-styler',
        properties: {
            text: 'text',
            color: 'color',
            size: 'size',
            textDecoration: 'text-decoration',
            enableNewTabIcon: 'enable-new-tab-icon'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwBadgeEvents = NonNullable<unknown>;

export const TnwBadge: StencilReactComponent<TnwBadgeElement, TnwBadgeEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwBadgeElement, TnwBadgeEvents>({
        tagName: 'tnw-badge',
        elementClass: TnwBadgeElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwBadgeEvents,
        defineCustomElement: defineTnwBadge
    })
    : /*@__PURE__*/ createSSRComponent<TnwBadgeElement, TnwBadgeEvents>({
        tagName: 'tnw-badge',
        properties: {
            label: 'label',
            variant: 'variant',
            appearance: 'appearance',
            appearanceColor: 'appearance-color',
            size: 'size',
            borderRadius: 'border-radius',
            imageSrc: 'image-src'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwBannerEvents = NonNullable<unknown>;

export const TnwBanner: StencilReactComponent<TnwBannerElement, TnwBannerEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwBannerElement, TnwBannerEvents>({
        tagName: 'tnw-banner',
        elementClass: TnwBannerElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwBannerEvents,
        defineCustomElement: defineTnwBanner
    })
    : /*@__PURE__*/ createSSRComponent<TnwBannerElement, TnwBannerEvents>({
        tagName: 'tnw-banner',
        properties: {
            appearance: 'appearance',
            appearanceColor: 'appearance-color',
            enableContentSlot: 'enable-content-slot',
            alignment: 'alignment',
            textAlignment: 'text-alignment',
            borderRadius: 'border-radius',
            margin: 'margin',
            paddingHorizontal: 'padding-horizontal',
            paddingVertical: 'padding-vertical',
            gap: 'gap',
            layout: 'layout',
            disableInternalContainer: 'disable-internal-container'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwButtonEvents = NonNullable<unknown>;

export const TnwButton: StencilReactComponent<TnwButtonElement, TnwButtonEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwButtonElement, TnwButtonEvents>({
        tagName: 'tnw-button',
        elementClass: TnwButtonElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwButtonEvents,
        defineCustomElement: defineTnwButton
    })
    : /*@__PURE__*/ createSSRComponent<TnwButtonElement, TnwButtonEvents>({
        tagName: 'tnw-button',
        properties: {
            label: 'label',
            type: 'type',
            appearanceColor: 'appearance-color',
            appearance: 'appearance',
            size: 'size',
            hoverAppearance: 'hover-appearance',
            hoverAppearanceColor: 'hover-appearance-color',
            hoverEffect: 'hover-effect',
            href: 'href',
            newTab: 'new-tab',
            disabled: 'disabled',
            borderRadius: 'border-radius'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwCardEvents = NonNullable<unknown>;

export const TnwCard: StencilReactComponent<TnwCardElement, TnwCardEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwCardElement, TnwCardEvents>({
        tagName: 'tnw-card',
        elementClass: TnwCardElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwCardEvents,
        defineCustomElement: defineTnwCard
    })
    : /*@__PURE__*/ createSSRComponent<TnwCardElement, TnwCardEvents>({
        tagName: 'tnw-card',
        properties: {
            imageSrc: 'image-src',
            imageAlt: 'image-alt',
            imageHeight: 'image-height',
            heading: 'heading',
            subheading: 'subheading',
            description: 'description',
            buttonLabel: 'button-label',
            buttonHref: 'button-href',
            buttonRadius: 'button-radius',
            date: 'date',
            badgeLabel: 'badge-label',
            textAlignment: 'text-alignment',
            itemsAlignment: 'items-alignment',
            spacing: 'spacing',
            contentSpacing: 'content-spacing',
            padding: 'padding',
            appearance: 'appearance',
            appearanceColor: 'appearance-color',
            orderContentFirst: 'order-content-first',
            layout: 'layout',
            borderRadius: 'border-radius',
            useGlassmorphismEffect: 'use-glassmorphism-effect',
            enableImageSlot: 'enable-image-slot',
            enableContentSlot: 'enable-content-slot',
            largerImage: 'larger-image'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwContactBannerEvents = NonNullable<unknown>;

export const TnwContactBanner: StencilReactComponent<TnwContactBannerElement, TnwContactBannerEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwContactBannerElement, TnwContactBannerEvents>({
        tagName: 'tnw-contact-banner',
        elementClass: TnwContactBannerElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwContactBannerEvents,
        defineCustomElement: defineTnwContactBanner
    })
    : /*@__PURE__*/ createSSRComponent<TnwContactBannerElement, TnwContactBannerEvents>({
        tagName: 'tnw-contact-banner',
        properties: {
            appearance: 'appearance',
            appearanceColor: 'appearance-color',
            enableContentSlot: 'enable-content-slot',
            alignment: 'alignment',
            textAlignment: 'text-alignment',
            borderRadius: 'border-radius',
            margin: 'margin',
            paddingHorizontal: 'padding-horizontal',
            paddingVertical: 'padding-vertical',
            gap: 'gap',
            layout: 'layout',
            disableInternalContainer: 'disable-internal-container'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwCopyrightsFooterEvents = NonNullable<unknown>;

export const TnwCopyrightsFooter: StencilReactComponent<TnwCopyrightsFooterElement, TnwCopyrightsFooterEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwCopyrightsFooterElement, TnwCopyrightsFooterEvents>({
        tagName: 'tnw-copyrights-footer',
        elementClass: TnwCopyrightsFooterElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwCopyrightsFooterEvents,
        defineCustomElement: defineTnwCopyrightsFooter
    })
    : /*@__PURE__*/ createSSRComponent<TnwCopyrightsFooterElement, TnwCopyrightsFooterEvents>({
        tagName: 'tnw-copyrights-footer',
        properties: {
            startYear: 'start-year',
            endYear: 'end-year',
            useCurrentYearAsStartYear: 'use-current-year-as-start-year',
            useCurrentYearAsEndYear: 'use-current-year-as-end-year',
            organizationName: 'organization-name',
            organizationNameColor: 'organization-name-color',
            preText: 'pre-text',
            postText: 'post-text',
            textColor: 'text-color',
            backgroundColor: 'background-color',
            borderTopColor: 'border-top-color',
            centerContent: 'center-content',
            disableInternalContainer: 'disable-internal-container',
            useDivAsContainer: 'use-div-as-container',
            linksData: 'links-data',
            useCustomLinks: 'use-custom-links',
            linksLength: 'links-length'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwDividerEvents = NonNullable<unknown>;

export const TnwDivider: StencilReactComponent<TnwDividerElement, TnwDividerEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwDividerElement, TnwDividerEvents>({
        tagName: 'tnw-divider',
        elementClass: TnwDividerElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwDividerEvents,
        defineCustomElement: defineTnwDivider
    })
    : /*@__PURE__*/ createSSRComponent<TnwDividerElement, TnwDividerEvents>({
        tagName: 'tnw-divider',
        properties: {
            variant: 'variant',
            color: 'color'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwFooterEvents = NonNullable<unknown>;

export const TnwFooter: StencilReactComponent<TnwFooterElement, TnwFooterEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwFooterElement, TnwFooterEvents>({
        tagName: 'tnw-footer',
        elementClass: TnwFooterElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwFooterEvents,
        defineCustomElement: defineTnwFooter
    })
    : /*@__PURE__*/ createSSRComponent<TnwFooterElement, TnwFooterEvents>({
        tagName: 'tnw-footer',
        properties: {
            backgroundColor: 'background-color',
            borderTopColor: 'border-top-color',
            padding: 'padding',
            margin: 'margin',
            headingColor: 'heading-color',
            textColor: 'text-color',
            disableInternalContainer: 'disable-internal-container',
            centerContent: 'center-content',
            footerData: 'footer-data'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwHeaderEvents = NonNullable<unknown>;

export const TnwHeader: StencilReactComponent<TnwHeaderElement, TnwHeaderEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwHeaderElement, TnwHeaderEvents>({
        tagName: 'tnw-header',
        elementClass: TnwHeaderElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwHeaderEvents,
        defineCustomElement: defineTnwHeader
    })
    : /*@__PURE__*/ createSSRComponent<TnwHeaderElement, TnwHeaderEvents>({
        tagName: 'tnw-header',
        properties: {
            disableInternalContainer: 'disable-internal-container',
            backgroundColor: 'background-color',
            borderBottomColor: 'border-bottom-color',
            height: 'height',
            minHeight: 'min-height',
            alignment: 'alignment',
            centerBanner: 'center-banner'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwHeaderBannerEvents = NonNullable<unknown>;

export const TnwHeaderBanner: StencilReactComponent<TnwHeaderBannerElement, TnwHeaderBannerEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwHeaderBannerElement, TnwHeaderBannerEvents>({
        tagName: 'tnw-header-banner',
        elementClass: TnwHeaderBannerElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwHeaderBannerEvents,
        defineCustomElement: defineTnwHeaderBanner
    })
    : /*@__PURE__*/ createSSRComponent<TnwHeaderBannerElement, TnwHeaderBannerEvents>({
        tagName: 'tnw-header-banner',
        properties: {
            heading: 'heading',
            subheading: 'subheading',
            description: 'description',
            buttonLabel: 'button-label',
            theme: 'theme',
            alignment: 'alignment',
            width: 'width',
            contentWidth: 'content-width',
            contentMaxWidth: 'content-max-width',
            stickyNavbar: 'sticky-navbar',
            enableImageSlot: 'enable-image-slot',
            imageSrc: 'image-src',
            imageAlt: 'image-alt',
            wrapImage: 'wrap-image',
            imageBorderRadius: 'image-border-radius',
            disableInternalContainer: 'disable-internal-container',
            verticalCenter: 'vertical-center'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwHeadingEvents = NonNullable<unknown>;

export const TnwHeading: StencilReactComponent<TnwHeadingElement, TnwHeadingEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwHeadingElement, TnwHeadingEvents>({
        tagName: 'tnw-heading',
        elementClass: TnwHeadingElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwHeadingEvents,
        defineCustomElement: defineTnwHeading
    })
    : /*@__PURE__*/ createSSRComponent<TnwHeadingElement, TnwHeadingEvents>({
        tagName: 'tnw-heading',
        properties: {
            text: 'text',
            highlight: 'highlight',
            highlightColor: 'highlight-color',
            highlightWeight: 'highlight-weight',
            highlightTag: 'highlight-tag',
            level: 'level',
            headingTag: 'heading-tag',
            alignment: 'alignment',
            color: 'color',
            weight: 'weight',
            size: 'size',
            textCase: 'text-case',
            lineHeight: 'line-height',
            widthSize: 'width-size',
            useTextFont: 'use-text-font'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwIconEvents = NonNullable<unknown>;

export const TnwIcon: StencilReactComponent<TnwIconElement, TnwIconEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwIconElement, TnwIconEvents>({
        tagName: 'tnw-icon',
        elementClass: TnwIconElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwIconEvents,
        defineCustomElement: defineTnwIcon
    })
    : /*@__PURE__*/ createSSRComponent<TnwIconElement, TnwIconEvents>({
        tagName: 'tnw-icon',
        properties: {
            name: 'name',
            appearanceColor: 'appearance-color',
            appearance: 'appearance',
            color: 'color',
            size: 'size',
            tooltip: 'tooltip',
            enableSvg: 'enable-svg',
            labelAria: 'label-aria',
            hiddenAria: 'hidden-aria',
            isButton: 'is-button',
            borderRadius: 'border-radius'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwImageEvents = NonNullable<unknown>;

export const TnwImage: StencilReactComponent<TnwImageElement, TnwImageEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwImageElement, TnwImageEvents>({
        tagName: 'tnw-image',
        elementClass: TnwImageElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwImageEvents,
        defineCustomElement: defineTnwImage
    })
    : /*@__PURE__*/ createSSRComponent<TnwImageElement, TnwImageEvents>({
        tagName: 'tnw-image',
        properties: {
            src: 'src',
            alt: 'alt',
            caption: 'caption',
            width: 'width',
            height: 'height',
            widthSize: 'width-size',
            heightSize: 'height-size',
            aspectRatio: 'aspect-ratio',
            objectPosition: 'object-position',
            objectFit: 'object-fit',
            lazyLoading: 'lazy-loading',
            borderRadius: 'border-radius',
            link: 'link'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwInputEvents = {
    onInputChanged: EventName<CustomEvent<string>>,
    onValidationFailed: EventName<CustomEvent<{ inputId: string; error: string }>>
};

export const TnwInput: StencilReactComponent<TnwInputElement, TnwInputEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwInputElement, TnwInputEvents>({
        tagName: 'tnw-input',
        elementClass: TnwInputElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onInputChanged: 'inputChanged',
            onValidationFailed: 'validationFailed'
        } as TnwInputEvents,
        defineCustomElement: defineTnwInput
    })
    : /*@__PURE__*/ createSSRComponent<TnwInputElement, TnwInputEvents>({
        tagName: 'tnw-input',
        properties: {
            label: 'label',
            inputId: 'input-id',
            type: 'type',
            placeholder: 'placeholder',
            appearance: 'appearance',
            appearanceColor: 'appearance-color',
            isLabelSrOnly: 'is-label-sr-only',
            name: 'name',
            value: 'value',
            isRequired: 'is-required',
            maxlength: 'maxlength',
            minlength: 'minlength',
            pattern: 'pattern',
            autoComplete: 'auto-complete',
            disabled: 'disabled',
            helpText: 'help-text',
            borderRadius: 'border-radius',
            sanitizeInput: 'sanitize-input'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwInputFormEvents = NonNullable<unknown>;

export const TnwInputForm: StencilReactComponent<TnwInputFormElement, TnwInputFormEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwInputFormElement, TnwInputFormEvents>({
        tagName: 'tnw-input-form',
        elementClass: TnwInputFormElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwInputFormEvents,
        defineCustomElement: defineTnwInputForm
    })
    : /*@__PURE__*/ createSSRComponent<TnwInputFormElement, TnwInputFormEvents>({
        tagName: 'tnw-input-form',
        properties: {},
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwItemsCarouselEvents = NonNullable<unknown>;

export const TnwItemsCarousel: StencilReactComponent<TnwItemsCarouselElement, TnwItemsCarouselEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwItemsCarouselElement, TnwItemsCarouselEvents>({
        tagName: 'tnw-items-carousel',
        elementClass: TnwItemsCarouselElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwItemsCarouselEvents,
        defineCustomElement: defineTnwItemsCarousel
    })
    : /*@__PURE__*/ createSSRComponent<TnwItemsCarouselElement, TnwItemsCarouselEvents>({
        tagName: 'tnw-items-carousel',
        properties: {
            hideControls: 'hide-controls',
            enableControlsSlots: 'enable-controls-slots',
            showEdgesShadows: 'show-edges-shadows',
            controlsSize: 'controls-size',
            fitWithContainer: 'fit-with-container',
            slidesCount: 'slides-count',
            slidesSize: 'slides-size'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwLabelEvents = NonNullable<unknown>;

export const TnwLabel: StencilReactComponent<TnwLabelElement, TnwLabelEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwLabelElement, TnwLabelEvents>({
        tagName: 'tnw-label',
        elementClass: TnwLabelElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwLabelEvents,
        defineCustomElement: defineTnwLabel
    })
    : /*@__PURE__*/ createSSRComponent<TnwLabelElement, TnwLabelEvents>({
        tagName: 'tnw-label',
        properties: {
            text: 'text',
            htmlFor: 'html-for',
            color: 'color',
            size: 'size',
            weight: 'weight',
            textCase: 'text-case',
            isSrOnly: 'is-sr-only'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwListEvents = NonNullable<unknown>;

export const TnwList: StencilReactComponent<TnwListElement, TnwListEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwListElement, TnwListEvents>({
        tagName: 'tnw-list',
        elementClass: TnwListElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwListEvents,
        defineCustomElement: defineTnwList
    })
    : /*@__PURE__*/ createSSRComponent<TnwListElement, TnwListEvents>({
        tagName: 'tnw-list',
        properties: {
            listData: 'list-data',
            markerPosition: 'marker-position',
            color: 'color',
            size: 'size',
            weight: 'weight',
            textCase: 'text-case',
            lineHeight: 'line-height'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwNavbarEvents = {
    onTnwMenuToggle: EventName<CustomEvent<{ isOpen: boolean }>>,
    onTnwMenuVisibilityChange: EventName<CustomEvent<{ isMenuHidden: boolean, windowWidth: number }>>,
    onTnwScrollChange: EventName<CustomEvent<{ scrollY: number }>>
};

export const TnwNavbar: StencilReactComponent<TnwNavbarElement, TnwNavbarEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwNavbarElement, TnwNavbarEvents>({
        tagName: 'tnw-navbar',
        elementClass: TnwNavbarElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onTnwMenuToggle: 'tnwMenuToggle',
            onTnwMenuVisibilityChange: 'tnwMenuVisibilityChange',
            onTnwScrollChange: 'tnwScrollChange'
        } as TnwNavbarEvents,
        defineCustomElement: defineTnwNavbar
    })
    : /*@__PURE__*/ createSSRComponent<TnwNavbarElement, TnwNavbarEvents>({
        tagName: 'tnw-navbar',
        properties: {
            appearance: 'appearance',
            appearanceColor: 'appearance-color',
            sticky: 'sticky',
            disableInternalContainer: 'disable-internal-container',
            scopeStylesToContainer: 'scope-styles-to-container',
            menuExactCenter: 'menu-exact-center',
            menuPlacement: 'menu-placement',
            togglerPlacement: 'toggler-placement',
            borderRadius: 'border-radius',
            paddingHorizontal: 'padding-horizontal',
            paddingVertical: 'padding-vertical',
            menuData: 'menu-data',
            enableCtaSlot: 'enable-cta-slot',
            enableLogoSlot: 'enable-logo-slot',
            enableMenuSlot: 'enable-menu-slot',
            enableSearchSlot: 'enable-search-slot',
            hideMenuBelow: 'hide-menu-below',
            enableLinkSlot: 'enable-link-slot',
            linksLength: 'links-length'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwPortfolioGridEvents = NonNullable<unknown>;

export const TnwPortfolioGrid: StencilReactComponent<TnwPortfolioGridElement, TnwPortfolioGridEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwPortfolioGridElement, TnwPortfolioGridEvents>({
        tagName: 'tnw-portfolio-grid',
        elementClass: TnwPortfolioGridElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwPortfolioGridEvents,
        defineCustomElement: defineTnwPortfolioGrid
    })
    : /*@__PURE__*/ createSSRComponent<TnwPortfolioGridElement, TnwPortfolioGridEvents>({
        tagName: 'tnw-portfolio-grid',
        properties: {
            itemsData: 'items-data',
            columns: 'columns',
            spacing: 'spacing',
            showGradientFade: 'show-gradient-fade'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwRatingEvents = NonNullable<unknown>;

export const TnwRating: StencilReactComponent<TnwRatingElement, TnwRatingEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwRatingElement, TnwRatingEvents>({
        tagName: 'tnw-rating',
        elementClass: TnwRatingElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwRatingEvents,
        defineCustomElement: defineTnwRating
    })
    : /*@__PURE__*/ createSSRComponent<TnwRatingElement, TnwRatingEvents>({
        tagName: 'tnw-rating',
        properties: {
            totalStars: 'total-stars',
            rating: 'rating',
            starSize: 'star-size',
            filledStarColor: 'filled-star-color',
            emptyStarColor: 'empty-star-color',
            hideEmptyStars: 'hide-empty-stars'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwRowsCarouselEvents = {
    onTnwRowPause: EventName<CustomEvent<number>>,
    onTnwRowResume: EventName<CustomEvent<number>>
};

export const TnwRowsCarousel: StencilReactComponent<TnwRowsCarouselElement, TnwRowsCarouselEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwRowsCarouselElement, TnwRowsCarouselEvents>({
        tagName: 'tnw-rows-carousel',
        elementClass: TnwRowsCarouselElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onTnwRowPause: 'tnwRowPause',
            onTnwRowResume: 'tnwRowResume'
        } as TnwRowsCarouselEvents,
        defineCustomElement: defineTnwRowsCarousel
    })
    : /*@__PURE__*/ createSSRComponent<TnwRowsCarouselElement, TnwRowsCarouselEvents>({
        tagName: 'tnw-rows-carousel',
        properties: {
            rows: 'rows',
            animationSpeed: 'animation-speed'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwScrollToTopEvents = {
    onVisible: EventName<CustomEvent<{ isVisible: boolean; scrollY: number }>>,
    onScrollToTopClicked: EventName<CustomEvent<{ scrollY: number }>>
};

export const TnwScrollToTop: StencilReactComponent<TnwScrollToTopElement, TnwScrollToTopEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwScrollToTopElement, TnwScrollToTopEvents>({
        tagName: 'tnw-scroll-to-top',
        elementClass: TnwScrollToTopElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onVisible: 'visible',
            onScrollToTopClicked: 'scrollToTopClicked'
        } as TnwScrollToTopEvents,
        defineCustomElement: defineTnwScrollToTop
    })
    : /*@__PURE__*/ createSSRComponent<TnwScrollToTopElement, TnwScrollToTopEvents>({
        tagName: 'tnw-scroll-to-top',
        properties: {
            size: 'size',
            appearanceColor: 'appearance-color',
            appearance: 'appearance',
            color: 'color',
            borderRadius: 'border-radius',
            customIconName: 'custom-icon-name',
            enableCustomSvgIcon: 'enable-custom-svg-icon'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwSearchInputEvents = { onInputChangedOnType: EventName<CustomEvent<string>> };

export const TnwSearchInput: StencilReactComponent<TnwSearchInputElement, TnwSearchInputEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwSearchInputElement, TnwSearchInputEvents>({
        tagName: 'tnw-search-input',
        elementClass: TnwSearchInputElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onInputChangedOnType: 'inputChangedOnType' } as TnwSearchInputEvents,
        defineCustomElement: defineTnwSearchInput
    })
    : /*@__PURE__*/ createSSRComponent<TnwSearchInputElement, TnwSearchInputEvents>({
        tagName: 'tnw-search-input',
        properties: {
            label: 'label',
            inputId: 'input-id',
            type: 'type',
            placeholder: 'placeholder',
            variant: 'variant',
            appearance: 'appearance',
            appearanceColor: 'appearance-color',
            name: 'name',
            value: 'value',
            autoComplete: 'auto-complete',
            borderRadius: 'border-radius',
            width: 'width'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwSectionEvents = NonNullable<unknown>;

export const TnwSection: StencilReactComponent<TnwSectionElement, TnwSectionEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwSectionElement, TnwSectionEvents>({
        tagName: 'tnw-section',
        elementClass: TnwSectionElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwSectionEvents,
        defineCustomElement: defineTnwSection
    })
    : /*@__PURE__*/ createSSRComponent<TnwSectionElement, TnwSectionEvents>({
        tagName: 'tnw-section',
        properties: {
            useGlassmorphismEffect: 'use-glassmorphism-effect',
            appearance: 'appearance',
            appearanceColor: 'appearance-color',
            disableInternalContainer: 'disable-internal-container',
            padding: 'padding',
            margin: 'margin',
            spacing: 'spacing',
            isFirstSection: 'is-first-section',
            isLastSection: 'is-last-section',
            alignment: 'alignment'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwSelectEvents = {
    onOptionSelected: EventName<TnwSelectCustomEvent<TnwSelectOption>>,
    onDropdownToggled: EventName<CustomEvent<{ isOpen: boolean }>>
};

export const TnwSelect: StencilReactComponent<TnwSelectElement, TnwSelectEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwSelectElement, TnwSelectEvents>({
        tagName: 'tnw-select',
        elementClass: TnwSelectElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onOptionSelected: 'optionSelected',
            onDropdownToggled: 'dropdownToggled'
        } as TnwSelectEvents,
        defineCustomElement: defineTnwSelect
    })
    : /*@__PURE__*/ createSSRComponent<TnwSelectElement, TnwSelectEvents>({
        tagName: 'tnw-select',
        properties: {
            optionsData: 'options-data',
            label: 'label',
            borderRadius: 'border-radius',
            size: 'size',
            disabled: 'disabled',
            fullWidth: 'full-width',
            accessibilityId: 'accessibility-id',
            variant: 'variant',
            optionAppearance: 'option-appearance'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwSubscriptionFormEvents = NonNullable<unknown>;

export const TnwSubscriptionForm: StencilReactComponent<TnwSubscriptionFormElement, TnwSubscriptionFormEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwSubscriptionFormElement, TnwSubscriptionFormEvents>({
        tagName: 'tnw-subscription-form',
        elementClass: TnwSubscriptionFormElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwSubscriptionFormEvents,
        defineCustomElement: defineTnwSubscriptionForm
    })
    : /*@__PURE__*/ createSSRComponent<TnwSubscriptionFormElement, TnwSubscriptionFormEvents>({
        tagName: 'tnw-subscription-form',
        properties: {
            buttonLabel: 'button-label',
            inputPlaceholder: 'input-placeholder',
            successMessage: 'success-message',
            borderRadius: 'border-radius',
            variant: 'variant',
            theme: 'theme',
            enableButtonSlot: 'enable-button-slot',
            inputId: 'input-id',
            formAction: 'form-action',
            formMethod: 'form-method',
            formAttributes: 'form-attributes'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwTestimonialCardEvents = NonNullable<unknown>;

export const TnwTestimonialCard: StencilReactComponent<TnwTestimonialCardElement, TnwTestimonialCardEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwTestimonialCardElement, TnwTestimonialCardEvents>({
        tagName: 'tnw-testimonial-card',
        elementClass: TnwTestimonialCardElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwTestimonialCardEvents,
        defineCustomElement: defineTnwTestimonialCard
    })
    : /*@__PURE__*/ createSSRComponent<TnwTestimonialCardElement, TnwTestimonialCardEvents>({
        tagName: 'tnw-testimonial-card',
        properties: {
            authorPhotoSrc: 'author-photo-src',
            authorPhotoAlt: 'author-photo-alt',
            authorName: 'author-name',
            authorRole: 'author-role',
            text: 'text',
            spacing: 'spacing',
            padding: 'padding',
            appearance: 'appearance',
            appearanceColor: 'appearance-color',
            borderRadius: 'border-radius',
            useGlassmorphismEffect: 'use-glassmorphism-effect',
            useRandomAvatar: 'use-random-avatar'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwTextEvents = NonNullable<unknown>;

export const TnwText: StencilReactComponent<TnwTextElement, TnwTextEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwTextElement, TnwTextEvents>({
        tagName: 'tnw-text',
        elementClass: TnwTextElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as TnwTextEvents,
        defineCustomElement: defineTnwText
    })
    : /*@__PURE__*/ createSSRComponent<TnwTextElement, TnwTextEvents>({
        tagName: 'tnw-text',
        properties: {
            text: 'text',
            highlight: 'highlight',
            highlightColor: 'highlight-color',
            highlightWeight: 'highlight-weight',
            highlightTag: 'highlight-tag',
            alignment: 'alignment',
            color: 'color',
            size: 'size',
            weight: 'weight',
            textCase: 'text-case',
            lineHeight: 'line-height',
            widthSize: 'width-size',
            textTag: 'text-tag',
            displayMode: 'display-mode'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });

type TnwTextareaEvents = {
    onTextareaChanged: EventName<CustomEvent<string>>,
    onValidationFailed: EventName<CustomEvent<{ textareaId: string; error: string }>>
};

export const TnwTextarea: StencilReactComponent<TnwTextareaElement, TnwTextareaEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<TnwTextareaElement, TnwTextareaEvents>({
        tagName: 'tnw-textarea',
        elementClass: TnwTextareaElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onTextareaChanged: 'textareaChanged',
            onValidationFailed: 'validationFailed'
        } as TnwTextareaEvents,
        defineCustomElement: defineTnwTextarea
    })
    : /*@__PURE__*/ createSSRComponent<TnwTextareaElement, TnwTextareaEvents>({
        tagName: 'tnw-textarea',
        properties: {
            label: 'label',
            textareaId: 'textarea-id',
            placeholder: 'placeholder',
            appearance: 'appearance',
            isLabelSrOnly: 'is-label-sr-only',
            name: 'name',
            value: 'value',
            isRequired: 'is-required',
            maxlength: 'maxlength',
            minlength: 'minlength',
            rows: 'rows',
            cols: 'cols',
            disabled: 'disabled',
            autoComplete: 'auto-complete',
            helpText: 'help-text',
            resize: 'resize',
            borderRadius: 'border-radius',
            sanitizeTextarea: 'sanitize-textarea'
        },
        hydrateModule: import('@technway/stencil-library/hydrate')
    });
