name: Main Workflow

env:
    ACTIONS_STEP_DEBUG: true

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    test:
        strategy:
            matrix:
                os: ["ubuntu-latest", "windows-latest"]

        if: ${{ !contains(github.event.head_commit.message, '[skip-test]') }}

        name: Run Tests ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        timeout-minutes: 30

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 9.15.3

            - name: Authenticate with npm
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20.11.0"
                  cache: "pnpm"

            - name: Install Dependencies
              run: pnpm install --loglevel=debug

            - name: Run Tests
              run: pnpm test:stencil

    root-versioning:
        if: ${{ !contains(github.event.head_commit.message, '[skip-versioning]') }}
        name: Versioning Root
        runs-on: ubuntu-latest
        needs:
            - test
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 9.15.3

            - name: Authenticate with npm
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Release Please
              uses: google-github-actions/release-please-action@v3
              with:
                  release-type: node
                  monorepo-tags: true
                  token: ${{ secrets.GITHUB_TOKEN }}
