name: Main Workflow

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    if: ${{ !contains(github.event.head_commit.message, '[skip-lint]') }}
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.3

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies for @technway/stencil-library
        working-directory: packages/stencil-library
        run: pnpm install

      - name: Run Lint
        run: pnpm lerna run lint --scope=@technway/stencil-library

  test:
    if: ${{ !contains(github.event.head_commit.message, '[skip-test]') }}
    name: Run Spec Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.3

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies for @technway/components
        working-directory: packages/stencil-library
        run: pnpm install

      - name: Run Tests
        run: pnpm lerna run test.spec

  versioning:
    if: ${{ !contains(github.event.head_commit.message, '[skip-versioning]') }}
    name: Versioning Packages
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          monorepo-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}
